#import <Foundation/Foundation.h>

/**
 This class represents a set of ARImageTrackable objects, typically imported from a .KARMarker file.
 */
@interface ARImageTrackableSet : NSObject

/**
 Initialise an ARImageTrackableSet with a trackable set file.
 
 Example of use:
 @code
 NSString *filePath = [[[NSBundle mainBundle] resourcePath] stringByAppendingString:@"example.KARMarker"];
 ARImageTrackableSet *imageTrackableSet = [[ARImageTrackable alloc] initWithPath:filePath];
 @endcode
 
 @param path The full path name to the trackable set file. This includes all folders and the file extension. This file should have been generated by the Kudan AR Toolkit and be in the .KARMarker format.
 */
- (instancetype)initWithPath:(NSString *)path;

/**
 Initialise an ARImageTrackableSet with a trackable set file.
 
 Example of use:
 @code
 ARImageTrackableSet *trackableSet = [[ARImageTrackableSet alloc] initWithPath:@"Assets/example.KARMarker"];
 @endcode
 
 @param file The file relative to the main bundle, including the file extension. This file should have been generated using the Kudan AR Toolkit and be in the .KARMarker format.
 */
- (instancetype)initWithBundledFile:(NSString *)file;

/**
 The number of trackables in this set.
 */
@property (nonatomic, readonly) NSUInteger numberOfTrackables;

/**
 The list of ARImageTrackable objects in this set.
 */
@property (nonatomic, readonly) NSArray *trackables;

/**
 Set this marker set to use flow recovery, if the global setting is switched on (default to global setting).
 This applies to all markers in the set. To alter a specific marker within the set, it is necessary to take the trackable from the list and set it individually.
 
 Example of use:
 @code
 ARImageTrackableSet *trackableSet = [[ARImageTrackableSet alloc] initWithPath:@"Assets/example.KARMarker"];
 [trackableSet allowRecoveryMode];
 @endcode
 */
- (void)allowRecoveryMode;

/**
 Make this marker set use flow recovery irrespective of the global setting. This applies to all markers in the set.
 
 Example of use:
 @code
 ARImageTrackableSet *trackableSet = [[ARImageTrackableSet alloc] initWithPath:@"Assets/example.KARMarker"];
 [trackableSet forceRecoveryMode];
 @endcode
 */
- (void)forceRecoveryMode;

/**
 Prevent this set marker from using flow recovery, irrespective of the global setting. This applies to all markers in the set.
 
 Example of use:
 @code
 ARImageTrackableSet *trackableSet = [[ARImageTrackableSet alloc] initWithPath:@"Assets/example.KARMarker"];
 [trackableSet prohibitRecoveryMode];
 @endcode
 */
- (void)prohibitRecoveryMode;



@end
